version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: monitorpricesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  monitorprices:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitorprices_container
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: monitorpricesdb
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=monitorpricesdb;Username=myuser;Password=mypassword"
    ports:
      - "8080:8080"
      - "8081:8081"

  controlpanel:
    build:
      context: ./ControlPanel
      dockerfile: Dockerfile
    container_name: controlpanel_container
    depends_on:
      - monitorprices
    environment:
      API_URL: "http://monitorprices:8080" # ControlPanel usa esto para llamar a la API
    ports:
      - "5001:5001"

volumes:
  postgres_data:
