version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: monitorpricesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  monitorprices-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitorprices_api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=monitorpricesdb;Username=myuser;Password=mypassword"
    ports:
      - "8080:8080"

  controlpanel:
    build:
      context: .
      dockerfile: ControlPanel/Dockerfile
    container_name: controlpanel
    depends_on:
      - monitorprices-api
    environment:
      API_URL: "http://monitorprices-api:8080"
      ASPNETCORE_URLS: "http://+:5001"  
    ports:
      - "5001:5001"

volumes:
  postgres_data:
